config/routes.rb
QuantifiedDance::Application.routes.draw do
  resources :charts

  resources :songs

  resources :profiles do
    resources :plays
  end

  root 'profiles#index'

end

app/models/chart.rb
class Chart < ActiveRecord::Base
  belongs_to :song
  has_many :plays
  has_many :profiles, -> { uniq }, through: :plays

  def friendly_steps_type
    {
      'dance-single' => 'Single',
      'dance-double' => 'Double',
      'dance-couple' => 'Couple',
      'dance-solo'   => 'Solo'
    }[steps_type]
  end

  def friendly_description
    "#{friendly_steps_type} #{difficulty} (#{meter})"
  end
end

app/models/play.rb
class Play < ActiveRecord::Base
  belongs_to :profile
  belongs_to :chart
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  has_many :plays
end

app/models/song.rb
class Song < ActiveRecord::Base
  has_many :charts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/charts_controller.rb
class ChartsController < ApplicationController
end

app/controllers/plays_controller.rb
class PlaysController < ApplicationController
  def index
    @date = ((params[:date].to_date rescue nil) or Date.today)
    @profile = Profile.find(params[:profile_id])
    @plays = @profile.plays.where(played_at: @date.to_time..@date.to_time.end_of_day)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def index
    @profiles = Profile.all
  end

  def show
    @profile = Profile.find(params[:id])
    # XXX Boo hiss hardcoded time zone
    @recent_days = @profile.plays.
      select("date(played_at at time zone 'UTC' at time zone 'EST5EDT') as date," +
             "count(1) as num, sum(survive_seconds) as secs").
             group('date').order('date desc').limit(10)
    # 1+n but .include() kills the count :( at least n <= 10
    @favorite_songs = @profile.plays.joins(:chart).
      select('count(1) as num_plays, chart_id').
      group('chart_id').order('num_plays desc').limit(5)
  end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  def index
    @songs = Song.all
  end
  
  def show
    @song = Song.find(params[:id])
    @charts = @song.charts
    if params[:chart_id].present?
      @chart = @charts.find(params[:chart_id])
    else
      @chart = @charts.first
    end

    if params[:profile_id].present?
      @profile = Profile.find(params[:profile_id])
    end
    
    @plays = @chart.plays
    if @profile.present?
      @plays = @plays.find_all_by_profile_id(@profile)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def relative_date(date)
    diff = (date - Date.today).to_i
    if diff == 0
      "today"
    elsif diff == -1
      "yesterday"
    elsif diff == 1
      "tomorrow"
    elsif diff < 0
      "#{-diff} days ago"
    else
      "#{diff} days from now"
    end
  end

  def grade_name(grade)
    {
      "Tier01" => "AAAA",
      "Tier02" => "AAA",
      "Tier03" => "AA",
      "Tier04" => "A",
      "Tier05" => "B",
      "Tier06" => "C",
      "Tier07" => "D",
      "Failed" => "E",
      "NoData" => "No Data"
    }[grade]
  end

  def duration_as_min_sec(seconds, long = false)
    mins = (seconds / 60).floor
    secs = (seconds % 60).round
    if long
      "#{mins} minutes, #{secs} seconds"
    else
      "#{mins}m #{secs}s"
    end
  end
end

app/helpers/charts_helper.rb
module ChartsHelper
end

app/helpers/plays_helper.rb
module PlaysHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/charts/_chart.html.erb
<div><strong><big><%= chart.difficulty %></big></strong></div>
<div><strong><%= chart.meter %> foot</strong></div>
<div><%= chart.friendly_steps_type %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Quantified Dance</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <%= link_to "Quantified Dance", root_path, :class => "navbar-brand" %>
      </div>
      <ul class="nav navbar-nav">
        <li><%= link_to "Profiles", profiles_path %></li>
        <li><%= link_to "Songs", songs_path %></li>
      </ul>
    </div>
  </nav>

  <div class="container">
    <%= yield %>
  </div>

</body>
</html>

app/views/plays/index.html.erb
<ul class="pager pull-right">
  <li><%= link_to "&larr;".html_safe, date: @date - 1.day %></li>
  <li><strong><big>&nbsp;<%= l @date, format: :long %>&nbsp;</big></strong></li>
  <li><%= link_to "&rarr;".html_safe, date: @date + 1.day %></li>
  <li><%= link_to "Today", date: Date.today %></li>
</ul>

<h2>Songs played by <%= @profile.name %></h2>

<div class="lead">
  Danced <%= pluralize @plays.length, 'song' %> totaling
  <%= duration_as_min_sec(@plays.sum(:survive_seconds), true) %>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Time</th>
      <th>Song</th>
      <th>Difficulty</th>
      <th>Survived</th>
      <th>Grade</th>
    </tr>
  </thead>
  <tbody>
    <% @plays.each do |play| %>
    <tr>
      <td><big><%= l play.played_at, format: :time_only %></big></td>
      <td>
        <%= link_to song_path(play.chart.song, chart_id: play.chart, profile_id: @profile) do %>
          <%= render partial: 'songs/song', object: play.chart.song %>
        <% end %>
      </td>
      <td>
        <%= render partial: 'charts/chart', object: play.chart %>
      </td>
      <td>
        <big>
          <%= number_with_precision(play.survive_seconds, :precision => 0) %>s
        </big>
      </td>
      <td>
        <div><big><strong><%= grade_name(play.grade) %></strong></big></div>
        <div><%= number_to_percentage(play.percent_dp * 100, :precision => 2) %></div>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/profiles/index.html.erb
<h2>Profiles</h2>

<div class="row">
  <% @profiles.each do |profile| %>
    <div class="col-md-4">
      <div class="panel panel-default">
        <div class="panel-body">
          <big><strong><%= link_to profile.name, profile %></strong></big>
          <div>Last played <%= relative_date(profile.last_played_on) %></div>
          <div>Total play time <%= distance_of_time_in_words profile.total_play_seconds %></div>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/profiles/show.html.erb
<h2><%= @profile.name %></h2>

<div class="row">
  <div class="col-md-6">
    <h3>Recent Days</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Day</th>
          <th>Songs</th>
          <th>Time</th>
        </tr>
      </thead>
      <tbody>
        <% @recent_days.each do |day| %>
          <tr>
            <td>
              <big><strong><%= link_to l(day.date.to_date, format: :long),
                    profile_plays_path(@profile, date: day.date.to_date) %>
              </strong></big>
            </td>
            <td><big><%= day.num %></big></td>
            <td><big><%= duration_as_min_sec day.secs %></big></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <div class="col-md-6">
    <h3>Favorite Songs</h3>
    <table class="table table-hover">
      <thead>
        <tr>
          <th>Song</th>
          <th>Difficulty</th>
          <th>Plays</th>
        </tr>
      </thead>
      <tbody>
        <% @favorite_songs.each do |fav| %>
          <tr>
            <td>
              <%= link_to song_path(fav.chart.song, chart_id: fav.chart, profile_id: @profile) do %>
                <%= render partial: 'songs/song', object: fav.chart.song %>
              <% end %>
            </td>
            <td><%= render partial: 'charts/chart', object: fav.chart %></td>
            <td><big><strong><%= fav.num_plays %></strong></big></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/songs/_song.html.erb
<div>
  <strong><big><%= song.title %></big></strong>
  <small><em><%= song.subtitle %></em></small>
</div>
<div><%= song.artist %></div>
<div><small><%= song.group %></small></div>

app/views/songs/index.html.erb
<h2>Songs</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Group</th>
    </tr>
  </thead>
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= link_to song.title, song %> <small><%= song.subtitle %></small></td>
        <td><%= song.artist %></td>
        <td><%= song.group %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/songs/show.html.erb
<div class="page-header">
  <h2><%= @song.title %> <small><%= @song.subtitle %></small></h2>

  <div><big><strong><%= @song.artist %></strong></big></div>
  <div><big><%= @song.group %></big></div>
</div>

<div class="row">
  <div class="col-md-3">
    <ul class="nav nav-pills nav-stacked">
      <% @charts.each do |chart| %>
        <li class="<%= 'active' if chart == @chart %>">
          <%= link_to chart.friendly_description, chart_id: chart, profile_id: @profile %>
        </li>
      <% end %>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="dropdown pull-right">
      <button class="btn btn-lg btn-link dropdown-toggle" type="button" id="plays-profile-dropdown" data-toggle="dropdown">
        Newest first
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu dropdown-menu-right" role="menu" aria-labelledby="plays-profile-dropdown">
        <li role="presentation"><a role="menuitem" tabindex="-1" href="#">Action</a></li>
      </ul>
    </div>

    <div class="dropdown pull-left">
      <button class="btn btn-lg btn-link dropdown-toggle" type="button" id="plays-profile-dropdown" data-toggle="dropdown">
        <% if @profile.nil? %>
          Everyone's plays
        <% else %>
          Plays by <%= @profile.name %>
        <% end %>
        <span class="caret"></span>
      </button>
      <ul class="dropdown-menu" role="menu" aria-labelledby="plays-profile-dropdown">
        <li role="presentation">
          <%= link_to "Everyone's plays", chart_id: @chart, profile_id: nil %>
        </li>
        <% @chart.profiles.each do |profile| %>
          <li role="presentation">
            <%= link_to "Plays by #{profile.name}", chart_id: @chart, profile_id: profile %>
          </li>
        <% end %>
      </ul>
    </div>

    <div class="clearfix"></div>

    <table class="table table-striped">
      <thead>
        <tr>
          <th>Profile</th>
          <th>Time</th>
          <th>Survived</th>
          <th>Grade</th>
          <th>Percent</th>
        </tr>
      </thead>
      <tbody>
        <% @plays.each do |play| %>
          <tr>
            <td>
              <big>
                <% if play.profile.present? %>
                  <%= link_to play.profile.name, play.profile %>
                <% else %>
                  <em>no profile</em>
                <% end %>
              </big>
            </td>
            <td><big><%= l play.played_at %></big></td>
            <td>
              <big>
                <%= number_with_precision(play.survive_seconds, :precision => 0) %>s
              </big>
            </td>
            <td>
              <big><strong><%= grade_name(play.grade) %></strong></big>
            </td>
            <td>
              <big><%= number_to_percentage(play.percent_dp * 100, :precision => 2) %></big>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>